from odoo import api, fields, models
import logging

_logger = logging.getLogger(__name__)

class ScContentIdea(models.Model):
    _name = 'sc.content.idea'
    _description = 'Content Ideas generated by Research Agent'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'create_date desc'
    _rec_name = 'name'

    name = fields.Char(
        string="Article Title", 
        required=True, 
        tracking=True,
        translate=True,
        help="The title of the source article/news"
    )
    
    url = fields.Char(
        string="Source URL", 
        required=True,
        help="The full URL to the source article"
    )
    
    publish_date = fields.Date(
        string="Publication Date",
        help="The publication date of the source article"
    )
    
    summary = fields.Text(
        string="Summary", 
        required=True, 
        tracking=True,
        translate=True,
        help="A concise summary generated by the research agent"
    )
    
    task_id = fields.Many2one(
        'sc.content.idea.task',
        string="Generation Task",
        ondelete='cascade',
        help="Link to the generation task that created this idea"
    )
    
    # Computed fields for better UX
    word_count = fields.Integer(
        string="Summary Word Count",
        compute='_compute_word_count',
        store=True,
        help="Number of words in the summary"
    )
    
    domain_name = fields.Char(
        string="Source Domain",
        compute='_compute_domain_name',
        store=True,
        help="Domain name extracted from the URL"
    )
    
    keywords = fields.Char(
        string="Keywords",
        help="Relevant keywords extracted from the content idea"
    )
    
    state = fields.Selection([
        ('draft', 'Draft'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
        ('used', 'Used for Content')
    ], string="State", default='draft', tracking=True,
       help="Approval state of the content idea")
    
    @api.depends('summary')
    def _compute_word_count(self):
        """Compute word count of the summary"""
        for record in self:
            if record.summary:
                # Simple word count - split by whitespace
                words = len(record.summary.split())
                record.word_count = words
            else:
                record.word_count = 0
    
    @api.depends('url')
    def _compute_domain_name(self):
        """Extract domain name from URL"""
        for record in self:
            if record.url:
                try:
                    from urllib.parse import urlparse
                    parsed = urlparse(record.url)
                    record.domain_name = parsed.netloc
                except Exception:
                    record.domain_name = "Unknown"
            else:
                record.domain_name = ""
    
    def action_view_source(self):
        """Open the source URL in a new browser tab"""
        self.ensure_one()
        if self.url:
            return {
                'type': 'ir.actions.act_url',
                'url': self.url,
                'target': 'new',
            }
    
    def action_generate_content(self):
        """Open wizard to generate blog content from this idea"""
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'name': 'Generate Blog Content',
            'res_model': 'sc.generate.content.wizard',
            'view_mode': 'form',
            'target': 'new',
            'context': {
                'default_content_idea_id': self.id,
            }
        }
    
    def action_approve(self):
        """Approve the content idea"""
        self.ensure_one()
        self.state = 'approved'
        self.message_post(body="Content idea approved")
        return True
    
    def action_reject(self):
        """Reject the content idea"""
        self.ensure_one()
        self.state = 'rejected'
        self.message_post(body="Content idea rejected")
        return True
